### ISSUE TITLE
Ingest service stuck at block 0 

### ISSUE THREAD

**Issue by ayudh37** [subsquid/squid-template#67]
I am running a Macbook air with M1 chip but have replicated it with a macbook pro machine with intel chip.

After running the `docker compose -f archive/docker-compose.yml up` command, the archive-ingest-1 service gets stuck at the first block. I've attached an image of the output below.

<img width="1440" alt="Screenshot 2022-08-30 at 3 58 17 PM" src="https://user-images.githubusercontent.com/11541303/187382568-3f71c6a6-4e79-4ac4-94da-dc713d665508.png">

I am running a substrate node locally and have changed the command of the `ingest` service to "ws://host.docker.internal:9944". 

I can see my chain produce many blocks however even querying the `gateway` service with the below query gives blockHeight 0.
```
query {
   metadata {
      blockHeight
      blockHash
  } 
}
```

**Comment by eldargab** [comment]
Hey, seems like your chain doesn't finalise blocks!

Apart from that, you should use

```gql
query {
  status {
    head
  }
}
```

to get the number of indexed blocks. `.metadata` will always contain only one record unless there are runtime upgrades.

**Comment by ayudh37** [comment]
I see, btw the above query gave
```
{
  "data": {
    "status": {
      "head": 0
    }
  }
}
```

**Comment by eldargab** [comment]
Yes, according to logs ingester has indexed the genesis block and waits for further blocks, but it only consider finalised  ones.
